# Generated by Django 3.1.3 on 2020-11-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfileNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healthprofile.healthprofile')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='average_daily_nutrients',
            field=models.ManyToManyField(through='healthprofile.HealthProfileNutrient', to='food.Nutrient'),
        ),
    ]
