# Generated by Django 3.1.3 on 2020-11-24 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apigetcall',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='apisearchcall',
            options={'ordering': ['-timestamp']},
        ),
    ]
