# Generated by Django 3.1.3 on 2020-11-08 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutrient_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MemberCoach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coach_set', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MealFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servings', models.PositiveIntegerField()),
                ('food_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodproduct')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.meal')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='food_products',
            field=models.ManyToManyField(through='app.MealFood', to='app.FoodProduct'),
        ),
        migrations.AddField(
            model_name='meal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HealthProfileNutrient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('unit', models.CharField(max_length=50)),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.healthprofile')),
                ('nutrient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nutrient')),
            ],
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='average_daily_nutrients',
            field=models.ManyToManyField(through='app.HealthProfileNutrient', to='app.Nutrient'),
        ),
        migrations.AddField(
            model_name='healthprofile',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredients',
            field=models.ManyToManyField(to='app.Ingredient'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='nutrients',
            field=models.ManyToManyField(through='app.FoodNutrient', to='app.Nutrient'),
        ),
        migrations.AddField(
            model_name='foodnutrient',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.foodproduct'),
        ),
        migrations.AddField(
            model_name='foodnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.nutrient'),
        ),
    ]
