# Generated by Django 3.1.3 on 2020-11-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201108_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodproduct',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='foodproduct',
            name='nutrients',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='average_daily_nutrients',
        ),
        migrations.RemoveField(
            model_name='healthprofile',
            name='member',
        ),
        migrations.RemoveField(
            model_name='healthprofilenutrient',
            name='health_profile',
        ),
        migrations.RemoveField(
            model_name='healthprofilenutrient',
            name='nutrient',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food_products',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='member',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='food_product',
        ),
        migrations.RemoveField(
            model_name='mealfood',
            name='meal',
        ),
        migrations.DeleteModel(
            name='FoodNutrient',
        ),
        migrations.DeleteModel(
            name='FoodProduct',
        ),
        migrations.DeleteModel(
            name='HealthProfile',
        ),
        migrations.DeleteModel(
            name='HealthProfileNutrient',
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='MealFood',
        ),
        migrations.DeleteModel(
            name='Nutrient',
        ),
    ]
