# Generated by Django 3.1.3 on 2020-11-22 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.member'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='ingredients',
            field=models.ManyToManyField(to='food.Ingredient'),
        ),
        migrations.AddField(
            model_name='foodproduct',
            name='nutrients',
            field=models.ManyToManyField(through='food.FoodNutrient', to='food.Nutrient'),
        ),
        migrations.AddField(
            model_name='foodnutrient',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.foodproduct'),
        ),
        migrations.AddField(
            model_name='foodnutrient',
            name='nutrient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.nutrient'),
        ),
    ]
